baseURL = "https://y4code.com/"
languageCode = "zh-cn"
title = "属实 five 「部落格」"
theme = "contrast"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "AboutMe"
  weight = 30
  identifier = "aboutme"
  url = "/aboutme/"
# [[menu.main]]
#   name = "Tags"
#   weight = 30
#   identifier = "tags"
#   url = "/tags/"
# [[menu.main]]
#   name = "Categories"
#   weight = 40
#   identifier = "categories"
#   url = "/categories/"